apiVersion: v1
kind: Pod
metadata:
  name: productpage
spec:
  containers:
  - name: productpage
    image: istio/examples-bookinfo-productpage-v1
    env:
    - name: REVIEWS_HOSTNAME
      value: "10.244.0.27"
    - name: DETAILS_HOSTNAME
      value: "10.244.0.24"
    - name: RATINGS_HOSTNAME
      value: "10.244.0.23"
    ports:
    - containerPort: 9080